name: Create GitHub release

on:
  repository_dispatch:
    types: [create-github-release]


permissions:
  contents: read

jobs:
  Create_GitHub_release:
    permissions:
      contents: write  # for actions/create-release to create a release
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Create release for ${{ github.event.client_payload.ReleaseBranchName }}
      uses: actions/create-release@e9dc4ac22d57910765258fb6b199b62bfe0174da # v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.ReleaseBranchName }}
        release_name: ${{ github.event.client_payload.ReleaseTitle }}
        body: ${{ github.event.client_payload.ReleaseBody }}
        prerelease: ${{ github.event.client_payload.Prerelease }}
        commitish: ${{ github.event.client_payload.Commitish }}