name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


permissions:
  contents: write
  pull-requests: write

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0

    - name: Clone release branch to create pull request
      run: |
        git checkout ${{ github.event.client_payload.ReleaseBranchName }}
        git branch ${{ github.event.client_payload.ReleaseBranchName }}-docs
        git push origin ${{ github.event.client_payload.ReleaseBranchName }}-docs

    - name: Create pull request for ${{ github.event.client_payload.ReleaseBranchName }}
      id: create-pr
      uses: actions/github-script@4aed96e0ba636e3df2423e6887c9a83ef8522d6d # v2.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let response = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ github.event.client_payload.PullRequestTitle }}",
            head: "${{ github.event.client_payload.ReleaseBranchName }}-docs",
            base: "${{ github.event.client_payload.PullRequestBase }}",
            body: `${{ github.event.client_payload.PullRequestBody }}`
          });
          return response.data.number

    - name: Request reviewers
      uses: actions/github-script@4aed96e0ba636e3df2423e6887c9a83ef8522d6d # v2.1.0
      with:
        github-token: ${{secrets.PRAPPROVAL_SECRET}}
        script: |
          github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create-pr.outputs.result }},
              team_reviewers: ['runner-images-team']
          })
