# CI Validation

name: PowerShell Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'helpers/software-report-base/**'

permissions:
  contents: read

jobs:
  powershell-tests:
    name: PowerShell tests
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run Software Report module tests
        shell: pwsh
        run: |
            $ErrorActionPreference = "Stop"
            Invoke-Pester -Output Detailed "helpers/software-report-base/tests"
        