name: Update release

on:
  repository_dispatch:
    types: [update-github-release]


permissions:
  contents: write

jobs:
  Update_GitHub_release:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Update release for ${{ github.event.client_payload.ReleaseBranchName }}
      uses: actions/github-script@4aed96e0ba636e3df2423e6887c9a83ef8522d6d # v2.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const response = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ github.event.client_payload.ReleaseBranchName }}"
            });
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: response.data.id,
              prerelease: ${{ github.event.client_payload.Prerelease }}
            });
